#!/bin/bash

# build-di.sh - Build script for DI transformation

echo "🔧 Starting DI transformation..."

# Run the DI transformer
npx tsx tools/di-transformer.ts

if [ $? -eq 0 ]; then
    echo "✅ DI transformation completed successfully"
    echo "📁 Generated files:"
    echo "   - src/generated/di-config.ts"
    echo "   - src/services/AutoGeneratedRegistry.ts"
else
    echo "❌ DI transformation failed"
    exit 1
fi

echo "🏗️  Building application..."
npm run build

echo "🎉 Build completed!"