import React from 'react';
import { createRoot } from 'react-dom/client';
import { CompileTimeDIContainer } from '@tdi2/di-core';
import { DIProvider } from '@tdi2/di-core/context';
import App from './App';

// Import service implementations to register them
import './services/implementations/DashboardService';
import './services/implementations/AnalyticsService';
import './services/implementations/GraphService';
import './services/implementations/WebSocketService';
import './services/implementations/NotificationService';
import './services/implementations/ConfigService';

// Import styles
import './styles/dashboard.css';

// Create and configure the DI container
const container = new CompileTimeDIContainer();

// Load configuration if available (will be auto-generated by TDI2)
import('./.tdi2/di-config').then(({ DI_CONFIG }) => {
  container.loadConfiguration(DI_CONFIG);
}).catch(error => {
  console.warn('No DI configuration found, services will be registered manually');
  // Manual registration fallback - services are already imported above
});

const root = createRoot(document.getElementById('root')!);

root.render(
  <React.StrictMode>
    <DIProvider container={container}>
      <App />
    </DIProvider>
  </React.StrictMode>
);