import React from 'react';
import { createRoot } from 'react-dom/client';
import { DIContainer, DIProvider } from '@tdi2/di-core';
import App from './App';

// Import service implementations to register them
import './services/implementations/DashboardService';
import './services/implementations/AnalyticsService';
import './services/implementations/GraphService';
import './services/implementations/WebSocketService';
import './services/implementations/NotificationService';
import './services/implementations/ConfigService';

// Import styles
import './styles/dashboard.css';

// Create and configure the DI container
const container = new DIContainer();

// Load configuration if available (will be auto-generated by TDI2)
try {
  // This will be auto-generated by the TDI2 Vite plugin
  const { DI_CONFIG } = await import('./.tdi2/di-config');
  container.loadConfiguration(DI_CONFIG);
} catch (error) {
  console.warn('No DI configuration found, services will be registered manually');
  // Manual registration fallback - services are already imported above
}

const root = createRoot(document.getElementById('root')!);

root.render(
  <React.StrictMode>
    <DIProvider container={container}>
      <App />
    </DIProvider>
  </React.StrictMode>
);