import type { ProjectExample } from '../examples';

export interface TransformedFile {
  path: string;
  originalCode: string;
  transformedCode: string;
  error?: string;
}

export interface SandpackFiles {
  [key: string]: {
    code: string;
    hidden?: boolean;
    active?: boolean;
    readOnly?: boolean;
  };
}

/**
 * Generate Sandpack file structure with ORIGINAL source files + Vite plugin
 * This replicates what happens in real TDI2 projects like examples/tdi2-basic-example
 */
export function generateSandpackFiles(
  example: ProjectExample,
  transformedFiles: Record<string, TransformedFile>,
  diConfigContent: string
): SandpackFiles {
  const files: SandpackFiles = {};

  // Add package.json with @tdi2/vite-plugin-di
  files['/package.json'] = {
    code: JSON.stringify(
      {
        name: 'tdi2-playground-preview',
        version: '1.0.0',
        type: 'module',
        main: '/src/main.tsx',
        scripts: {
          dev: 'vite',
          build: 'vite build',
        },
        dependencies: {
          react: '^19.0.0',
          'react-dom': '^19.0.0',
          '@tdi2/di-core': '3.3.0',
          valtio: '^2.1.2',
        },
        devDependencies: {
          '@tdi2/vite-plugin-di': '3.3.0',
          '@vitejs/plugin-react': '^4.4.1',
          vite: '^6.0.0',
          typescript: '^5.0.2',
        },
      },
      null,
      2
    ),
    hidden: true,
  };

  // Add vite.config.ts with the actual DI plugin (just like the real example!)
  files['/vite.config.ts'] = {
    code: `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { diEnhancedPlugin } from '@tdi2/vite-plugin-di';

export default defineConfig({
  plugins: [
    diEnhancedPlugin({
      enableFunctionalDI: true,
      enableInterfaceResolution: true,
      generateDebugFiles: true,
    }),
    react(),
  ],
});
`,
    hidden: true,
  };

  // Add tsconfig.json
  files['/tsconfig.json'] = {
    code: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          useDefineForClassFields: true,
          lib: ['ES2020', 'DOM', 'DOM.Iterable'],
          module: 'ESNext',
          skipLibCheck: true,
          moduleResolution: 'bundler',
          allowImportingTsExtensions: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: 'react-jsx',
          strict: true,
          noUnusedLocals: true,
          noUnusedParameters: true,
          noFallthroughCasesInSwitch: true,
          experimentalDecorators: true,
        },
        include: ['src'],
      },
      null,
      2
    ),
    hidden: true,
  };

  // Add index.html
  files['/index.html'] = {
    code: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TDI2 Playground - ${example.name}</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.tsx"></script>
</body>
</html>`,
    hidden: true,
  };

  // Generate main.tsx entry point (imports auto-generated DI config)
  files['/src/main.tsx'] = {
    code: generateMainEntry(example),
    hidden: true,
    readOnly: true,
  };

  // Add ALL ORIGINAL untransformed files (let Vite plugin do the transformation!)
  for (const file of example.files) {
    const sandpackPath = `/src/${file.path.replace(/^src\//, '')}`;
    files[sandpackPath] = {
      code: file.content, // ✅ ORIGINAL untransformed source
      active: file === example.files[0],
    };
  }

  return files;
}

/**
 * Generate main.tsx entry point - matches examples/tdi2-basic-example/src/main.tsx
 */
function generateMainEntry(
  example: ProjectExample
): string {
  // Find the main component (first component file or first .tsx file)
  const mainComponent = findMainComponent(example);

  return `import React from 'react';
import { createRoot } from 'react-dom/client';
import { CompileTimeDIContainer } from '@tdi2/di-core/container';
import { DIProvider } from '@tdi2/di-core/context';
import { DI_CONFIG } from './.tdi2/di-config'; // Auto-generated by Vite plugin
import ${mainComponent.componentName} from './${mainComponent.path}';

// Create and configure DI container
const container = new CompileTimeDIContainer();
container.loadConfiguration(DI_CONFIG);

console.log('🔧 DI Container initialized');
console.log('📋 Registered services:', container.getRegisteredTokens());

createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <DIProvider container={container}>
      <${mainComponent.componentName} />
    </DIProvider>
  </React.StrictMode>
);
`;
}

/**
 * Find the main component to render
 */
function findMainComponent(example: ProjectExample): {
  componentName: string;
  path: string;
} {
  // Look for component files
  const componentFiles = example.files.filter((f) =>
    f.path.includes('components/')
  );

  if (componentFiles.length > 0) {
    const file = componentFiles[0];
    // Extract component name from file
    const nameMatch =
      file.content.match(/export default (\w+)/) ||
      file.content.match(/function (\w+)\s*\(/);

    return {
      componentName: nameMatch ? nameMatch[1] : 'App',
      path: file.path.replace(/^src\//, ''),
    };
  }

  // Fallback: use first .tsx file
  const tsxFile = example.files.find((f) => f.path.endsWith('.tsx'));
  if (tsxFile) {
    const nameMatch =
      tsxFile.content.match(/export default (\w+)/) ||
      tsxFile.content.match(/function (\w+)\s*\(/);

    return {
      componentName: nameMatch ? nameMatch[1] : 'App',
      path: tsxFile.path.replace(/^src\//, ''),
    };
  }

  // Last resort
  return {
    componentName: 'App',
    path: 'components/App.tsx',
  };
}
