# Leipzig.js Meetup Configuration
# Local React Meetup - Accessible and Practical  
extends: config.yaml

title: "Beyond Hooks Hell: How Service Injection Fixes React's Broken Architecture"
subtitle: "Leipzig.js Meetup - January 2025"

# Meetup-friendly settings
theme: "league"  # Dark theme works well in most venues
width: 1920     # Full HD standard
height: 1080

# Timing for 45-60 minute slot
defaultTiming: 90  # 1.5 minutes per slide average
autoSlide: 0       # Manual control for interactive elements
autoSlideStoppable: true

# Interactive presentation settings
controls: true
progress: true
fragments: true    # Enable step-by-step reveals for complex examples
fragmentInURL: false

customCSS: |
  /* Leipzig.js meetup styling */
  .reveal {
    font-size: 40px;  /* Larger font for venue visibility */
  }
  
  .reveal h1 {
    color: #61dafb;
    font-size: 2.4em;
    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.7);
  }
  
  .reveal h2 {
    color: #21a0c4;
    font-size: 1.8em;
    margin-bottom: 30px;
  }
  
  .reveal h3 {
    color: #ffd700;
    font-size: 1.4em;
  }
  
  /* Code blocks optimized for meetup projectors */
  .reveal pre code {
    font-size: 0.85em;
    line-height: 1.3;
    max-height: 65vh;
    border-radius: 8px;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
  }
  
  /* Interactive elements highlighting */
  .poll-question {
    background: rgba(97, 218, 251, 0.1);
    border: 2px solid #61dafb;
    border-radius: 10px;
    padding: 20px;
    margin: 20px 0;
    font-size: 1.1em;
  }
  
  .demo-highlight {
    background: rgba(255, 215, 0, 0.1);
    border: 2px solid #ffd700;
    border-radius: 8px;
    padding: 15px;
    margin: 15px 0;
  }
  
  /* Before/After comparison styling */
  .comparison-before {
    background: rgba(244, 67, 54, 0.1);
    border-left: 4px solid #f44336;
    padding: 15px;
    margin: 10px 0;
  }
  
  .comparison-after {
    background: rgba(76, 175, 80, 0.1);
    border-left: 4px solid #4caf50;
    padding: 15px;
    margin: 10px 0;
  }
  
  /* Community engagement elements */
  .community-highlight {
    background: rgba(156, 39, 176, 0.1);
    border: 1px solid #9c27b0;
    border-radius: 8px;
    padding: 20px;
    margin: 20px 0;
  }
  
  /* Leipzig.js specific branding */
  .leipzigjs-brand {
    color: #ff6b35;
    font-weight: bold;
  }
  
  /* Progress indicators for agenda sections */
  .agenda-section {
    position: absolute;
    top: 20px;
    right: 20px;
    background: rgba(0, 0, 0, 0.7);
    color: white;
    padding: 5px 10px;
    border-radius: 15px;
    font-size: 0.7em;
  }
  
  /* Simplified navigation for diverse audience */
  .reveal .controls {
    bottom: 20px;
    right: 20px;
    color: #61dafb;
  }
  
  .reveal .progress {
    height: 6px;
    color: #61dafb;
  }

# Slide numbering for speaker reference
slideNumber: true
slideNumberFormat: "Act %current% / %total%"

# PDF export settings for handouts
pdfMaxPagesPerSlide: 1
pdfSeparateFragments: false

# Notes configuration for speaker
notes:
  showNotes: false
  notesLayout: "separate-page"