import React from 'react';
import { createRoot } from 'react-dom/client';
import { CompileTimeDIContainer } from '@tdi2/di-core/container';
import { DIProvider } from '@tdi2/di-core/context';
import { DI_CONFIG } from './.tdi2/di-config'; // Auto-generated by plugin
import App from './App.tsx';

// Create and configure DI container
const container = new CompileTimeDIContainer();
container.loadConfiguration(DI_CONFIG);

console.log('🔧 DI Container initialized');
console.log('📋 Registered services:', container.getRegisteredTokens());

createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <DIProvider container={container}>
      <App />
    </DIProvider>
  </React.StrictMode>
);